name: mushrooms_classification_gpu
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - conda-forge::python=3.8.16
  - pip
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::cudatoolkit=11.3
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - numpy==1.21.6
    - tqdm==4.65.0
    - torchsummary==1.5.1
    - scikit-learn==1.0.2
    - matplotlib==3.4.3
    - Pillow==9.5.0
    - einops==0.6.1
    - tensorboard==2.12
    - streamlit==1.9.0
    - protobuf==3.20.3
    - click==8.0.0
    - altair==4.0.0
    - mlchain==0.3.0